name = "jizhang-system"
main = "index.py"
compatibility_date = "2025-07-01"
compatibility_flags = ["python_workers"]
account_id = "ef3d5ed4216ab2dd7c64dd679ce0b2cd"

[vars]
CF_PAGES = "1"
WORKER_RUNTIME = "cloudflare"
DISABLE_CAPTCHA = "1"

[python]
requirements = "./requirements.txt"
